"""phase 3 multi-tenant scoping

Revision ID: 4bc4a7720bdb
Revises: 
Create Date: 2026-09-17 18:57:09.957568
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4bc4a7720bdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_metadata',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('focus_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_company_metadata'))
    )
    with op.batch_alter_table('company_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_metadata_name'), ['name'], unique=False)

    op.create_table('problems',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('topics', sa.String(), nullable=False),
    sa.Column('companies', sa.String(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problems'))
    )
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problems_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_token', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('google_sub', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_device_token'), ['device_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('root_cause_category', sa.String(), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_attempts_problem_id_problems')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attempts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts'))
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('badge_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('problem1_id', sa.String(), nullable=False),
    sa.Column('problem2_id', sa.String(), nullable=False),
    sa.Column('problem1_solved', sa.Boolean(), nullable=False),
    sa.Column('problem2_solved', sa.Boolean(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_badge_tests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badge_tests'))
    )
    with op.batch_alter_table('badge_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badge_tests_user_id'), ['user_id'], unique=False)

    op.create_table('daily_activity',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('problems_attempted', sa.Integer(), nullable=False),
    sa.Column('problems_solved', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_activity_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'date', name=op.f('pk_daily_activity'))
    )
    op.create_table('spaced_repetition',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.String(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('last_solved', sa.DateTime(), nullable=False),
    sa.Column('next_due', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_spaced_repetition_problem_id_problems')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_spaced_repetition_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'problem_id', name=op.f('pk_spaced_repetition'))
    )
    with op.batch_alter_table('spaced_repetition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spaced_repetition_problem_id'), ['problem_id'], unique=False)

    op.create_table('topic_mastery',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_topic_mastery_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'topic', name=op.f('pk_topic_mastery'))
    )
    with op.batch_alter_table('topic_mastery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_mastery_topic'), ['topic'], unique=False)

    op.create_table('user_config',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_config_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'key', name=op.f('pk_user_config'))
    )
    with op.batch_alter_table('user_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_config_key'), ['key'], unique=False)

    op.create_table('user_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.String(), nullable=False),
    sa.Column('is_solved', sa.Boolean(), nullable=False),
    sa.Column('solved_live', sa.Boolean(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('personal_difficulty', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_user_problems_problem_id_problems')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_problems_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_problems')),
    sa.UniqueConstraint('user_id', 'problem_id', name='uq_user_problem')
    )
    with op.batch_alter_table('user_problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_problems_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_problems_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_problems_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_problems_problem_id'))

    op.drop_table('user_problems')
    with op.batch_alter_table('user_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_config_key'))

    op.drop_table('user_config')
    with op.batch_alter_table('topic_mastery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_mastery_topic'))

    op.drop_table('topic_mastery')
    with op.batch_alter_table('spaced_repetition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spaced_repetition_problem_id'))

    op.drop_table('spaced_repetition')
    op.drop_table('daily_activity')
    with op.batch_alter_table('badge_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badge_tests_user_id'))

    op.drop_table('badge_tests')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_id'))

    op.drop_table('attempts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_device_token'))

    op.drop_table('users')
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problems_id'))

    op.drop_table('problems')
    with op.batch_alter_table('company_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_metadata_name'))

    op.drop_table('company_metadata')
    # ### end Alembic commands ###
